"use client";
import { useMemo, useState } from "react";
import LiveCandlestickChart from "./components/LiveCandlestickChart";

const nav = ["Overview", "Markets", "Asset Allocation", "Strategy Lab", "Market Doctor", "News Intel", "Community", "Backtesting", "Forecast Accuracy", "Watchlist", "Economic Calendar", "Scenario Lab", "Learning"];
const bars = [42, 53, 45, 62, 57, 76, 68, 84, 80, 91, 86, 99];
const stocks = [
  ["RELIANCE", "₹2,942.60", "+1.42%", "up"], ["TCS", "₹3,881.20", "+0.68%", "up"],
  ["HDFCBANK", "₹1,628.40", "−0.37%", "down"], ["INFY", "₹1,461.55", "+2.08%", "up"]
];
const news = [
  ["Markets", "Nifty holds above 22,400 as banking stocks lead the session", "Bullish", "82"],
  ["Earnings", "Reliance expands green-energy investment roadmap", "Bullish", "76"],
  ["Macro", "RBI policy commentary keeps bond markets steady", "Neutral", "61"]
];

function Sparkline({ positive = true }: { positive?: boolean }) { return <svg viewBox="0 0 120 38" className="spark"><path d={positive ? "M2 31 C16 32,19 18,32 23 S48 9,60 17 S76 22,87 8 S104 10,118 3" : "M2 7 C17 2,24 16,37 12 S51 30,64 19 S79 25,91 26 S103 32,118 35"} fill="none" stroke={positive ? "#42d897" : "#ff697f"} strokeWidth="2.5" /></svg> }
function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`card ${className}`}>{children}</section> }

export default function Dashboard() {
  const [active, setActive] = useState("Overview");
  const [period, setPeriod] = useState("Today");
  const [query, setQuery] = useState("");
  const [watching, setWatching] = useState(false);
  const strategy = useMemo(() => ({ symbol: query || "RELIANCE", entry: "₹2,928", target: "₹3,055", stop: "₹2,870" }), [query]);
  return <main className="shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark">M</span><span>marketmind<span className="ai">.ai</span></span></div>
      <div className="workspace"><span className="avatar">SA</span><div><b>Sharma Analytics</b><small>Pro workspace</small></div><span className="chevron">⌄</span></div>
      <nav>{nav.map((n, i) => <button key={n} onClick={() => setActive(n)} className={active === n ? "active" : ""}><span className="nav-icon">{["⌘", "◈", "◐", "✦", "⊕", "◌", "◉", "⌁", "◫", "☆", "▣", "◒", "◇"][i]}</span>{n}{n === "News Intel" && <i>7</i>}</button>)}</nav>
      <div className="sidebar-bottom"><button><span className="nav-icon">?</span>Help center</button><button><span className="nav-icon">⚙</span>Settings</button><div className="upgrade"><span>✦</span><div><b>Unlock more insight</b><small>Upgrade to Pro</small></div><strong>›</strong></div></div>
    </aside>
    <div className="content">
      <header><div className="crumb">Workspace <span>/</span> <b>{active}</b></div><div className="header-actions"><button className="search">⌕ <span>Search a stock, news or concept</span><kbd>⌘ K</kbd></button><button className="icon-button">◌</button><button className="profile">SG <span>⌄</span></button></div></header>
      {active === "Overview" ? <><div className="page-head"><div><p className="eyebrow">MARKET OVERVIEW</p><h1>Good morning, Sagar <span>✦</span></h1><p className="sub">Here&apos;s the pulse of the Indian market today.</p></div><div className="period"><button onClick={() => setPeriod("Today")} className={period === "Today" ? "selected" : ""}>Today</button><button onClick={() => setPeriod("This week")} className={period === "This week" ? "selected" : ""}>This week</button><button className="calendar">▣</button></div></div>
      <div className="market-ticker"><div className="live"><span></span> MARKET LIVE</div><b>NIFTY 50</b><strong>22,493.55</strong><em>+187.40 (0.84%)</em><div className="ticker-line"/><b>SENSEX</b><strong>74,742.50</strong><em>+0.71%</em><div className="ticker-line"/><b>INDIA VIX</b><strong>12.84</strong><em className="red">−4.12%</em><div className="ticker-note">Last updated 2 mins ago <span>↻</span></div></div>
      <div className="chart-section"><LiveCandlestickChart /></div>
      <div className="grid top-grid"><Card className="market-card"><div className="card-title"><div><p>MARKET SENTIMENT</p><h2>Bullish <span className="pill green">↑ 12%</span></h2></div><button className="more">•••</button></div><div className="sentiment"><div className="gauge"><div className="gauge-inner"><b>72</b><small>/ 100</small></div></div><div className="legend"><p><span className="dot mint"/>Bullish <b>58%</b></p><p><span className="dot neutral"/>Neutral <b>26%</b></p><p><span className="dot red-dot"/>Bearish <b>16%</b></p><small>Based on technicals, news &amp; community</small></div></div><div className="market-foot"><span>AI confidence <b>High</b></span><button>View analysis <span>→</span></button></div></Card>
        <Card className="index-card"><div className="card-title"><div><p>BENCHMARK INDEX</p><h2>NIFTY 50</h2></div><span className="pill green">+0.84%</span></div><div className="index-price">22,493.55 <small>+187.40 today</small></div><div className="chart-area"><div className="chart-labels"><span>22.6k</span><span>22.4k</span><span>22.2k</span></div><svg viewBox="0 0 500 132" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#44d59b" stopOpacity=".28"/><stop offset="1" stopColor="#44d59b" stopOpacity="0"/></linearGradient></defs><path d="M0 99 C28 92 30 110 55 96 S86 98 106 82 S137 95 158 72 S190 95 210 68 S244 82 267 55 S288 66 314 46 S352 61 370 37 S405 54 431 32 S460 42 500 8 L500 132 L0 132Z" fill="url(#fill)"/><path d="M0 99 C28 92 30 110 55 96 S86 98 106 82 S137 95 158 72 S190 95 210 68 S244 82 267 55 S288 66 314 46 S352 61 370 37 S405 54 431 32 S460 42 500 8" fill="none" stroke="#48dc9f" strokeWidth="3"/></svg></div><div className="chart-times"><span>09:15</span><span>11:00</span><span>12:45</span><span>14:30</span><span>15:30</span></div></Card>
        <Card className="portfolio-card"><div className="card-title"><div><p>PORTFOLIO HEALTH</p><h2>Looking strong <span className="pulse"/></h2></div><button className="more">•••</button></div><div className="score-row"><div className="score"><b>82</b><span>Excellent</span></div><div><p>Overall score</p><div className="progress"><i/></div><small>+4 points this month</small></div></div><div className="portfolio-stats"><div><small>RISK LEVEL</small><b className="amber">Moderate</b></div><div><small>DIVERSIFICATION</small><b>Good</b></div></div><button className="outline-button">Open Market Doctor <span>→</span></button></Card></div>
      <div className="section-title"><div><p className="eyebrow">AI-POWERED INSIGHT</p><h2>Your market brief</h2></div><button className="link">View all insights <span>→</span></button></div>
      <div className="grid insight-grid"><Card className="strategy-card"><div className="strategy-top"><span className="feature-icon">✦</span><span className="label">STRATEGY SIGNAL</span><span className="pill green">High confidence</span></div><h3>{strategy.symbol}: Swing opportunity detected</h3><p>Strong momentum with a clean breakout above the 20-day EMA. Volume confirmation remains healthy.</p><div className="levels"><div><small>ENTRY ZONE</small><b>{strategy.entry}</b></div><div><small>TARGET</small><b className="mint-text">{strategy.target}</b></div><div><small>STOP LOSS</small><b className="red-text">{strategy.stop}</b></div><div><small>R:R</small><b>1 : 2.7</b></div></div><div className="strategy-bottom"><span><b>73%</b> probability · Swing · 3–7 days</span><button onClick={() => setQuery("")}>Explore strategy <span>→</span></button></div></Card>
        <Card className="accuracy-card"><div className="card-title"><div><p>MODEL PERFORMANCE</p><h3>Forecast accuracy <span className="pill green">↑ 3.2%</span></h3></div><button className="more">•••</button></div><div className="accuracy"><div><b>71.4%</b><span>Direction accuracy</span></div><div className="mini-bars">{bars.map((x,i) => <i key={i} style={{height:`${x}%`}} className={i > 7 ? "hot" : ""}/>)}</div></div><div className="accuracy-foot"><span>Powered by <b>XGBoost v2.1</b></span><button>View accuracy <span>→</span></button></div></Card></div>
      <div className="grid lower-grid"><Card className="watch-card"><div className="card-title"><div><p>WATCHLIST</p><h2>On your radar</h2></div><button className="add" onClick={() => setWatching(!watching)}>{watching ? "✓ Added" : "+ Add stock"}</button></div><div className="stock-table">{stocks.map(([name,price,change,dir]) => <div key={name}><span className="stock-logo">{name[0]}</span><b>{name}<small>NSE</small></b><strong>{price}</strong><span className={dir}>{change}</span><Sparkline positive={dir === "up"}/><button>⋮</button></div>)}</div></Card>
        <Card className="news-card"><div className="card-title"><div><p>NEWS INTELLIGENCE</p><h2>What&apos;s moving markets</h2></div><button className="more">•••</button></div>{news.map(([tag, title, mood, score]) => <article key={title}><span className={`news-tag ${mood.toLowerCase()}`}>{tag}</span><div><h4>{title}</h4><small>AI impact: <b className={mood === "Bullish" ? "mint-text" : ""}>{mood}</b> · Confidence {score}%</small></div><button>→</button></article>)}<button className="news-link">Open News Intelligence <span>→</span></button></Card></div>
      <footer><span>⚠ Predictions are AI-generated research insights and should not be considered financial advice.</span><span>MarketMind AI · v0.1.0</span></footer></> : <FeatureWorkspace active={active} />}
    </div>
  </main>;
}

function FeatureWorkspace({ active }: { active: string }) {
  const [symbol, setSymbol] = useState("RELIANCE");
  const [result, setResult] = useState("");
  const [selected, setSelected] = useState<string[]>(["RSI", "MACD", "EMA"]);
  const [chat, setChat] = useState("");
  const [mentorLoading, setMentorLoading] = useState(false);
  const [mentorError, setMentorError] = useState("");
  const [messages, setMessages] = useState<{from:string;text:string}[]>([{from:"AI Mentor", text:"Ask me to explain an indicator, market move, or strategy."}]);
  const toggle = (item: string) => setSelected(x => x.includes(item) ? x.filter(v => v !== item) : [...x, item]);
  const title: Record<string, [string,string]> = {"Markets":["Markets", "Live pricing, breadth, sectors and macro pulse."],"Asset Allocation":["AI Asset Allocation Advisor", "Build a diversified, adaptive investment plan for current market conditions."],"Strategy Lab":["AI Strategy Lab","Build a rule-based trade thesis with explainable AI."],"Market Doctor":["AI Market Doctor","Diagnose portfolio concentration, risk and quality."],"News Intel":["News Intelligence","Research the stories moving markets and their likely impact."],"Community":["Community Pulse","Social-market sentiment from Reddit and Stocktwits."],"Backtesting":["Strategy Backtesting","Validate an idea before risking capital."],"Forecast Accuracy":["Forecast accuracy", "Track model quality against real market outcomes."],"Watchlist":["Watchlist", "Monitor the names that matter to your process."],"Economic Calendar":["Economic calendar", "Know the macro and corporate events that can move markets."],"Scenario Lab":["Scenario simulator", "Explore possible market reactions before they happen."],"Learning":["Learning mode","Build practical market knowledge, one concept at a time."]};
  const [heading, description] = title[active] || [active, "Explore MarketMind intelligence."];
  const run = (message: string) => setResult(message);
  const askMentor = async (question = chat) => {
    const prompt = question.trim();
    if (!prompt || mentorLoading) return;
    setChat(""); setMentorError(""); setMentorLoading(true);
    setMessages(items => [...items, {from:"You", text:prompt}]);
    const offline = "I’m currently in offline research mode. Consider trend, momentum, volume, catalysts and a defined stop-loss before acting. I can explain RSI, MACD, portfolio risk, and market context without giving financial advice.";
    try {
      const api = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";
      const response = await fetch(`${api}/api/mentor/chat`, {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({message:prompt, symbol:symbol || undefined})});
      if (!response.ok) throw new Error("Mentor service unavailable");
      const data: {answer?: string} = await response.json();
      setMessages(items => [...items, {from:"AI Mentor", text:data.answer || offline}]);
    } catch {
      setMentorError("The live mentor service is offline, so an offline research response was used.");
      setMessages(items => [...items, {from:"AI Mentor", text:offline}]);
    } finally { setMentorLoading(false); }
  };
  return <div className="feature-page"><div className="page-head"><div><p className="eyebrow">MARKETMIND AI / {active.toUpperCase()}</p><h1>{heading}</h1><p className="sub">{description}</p></div></div>
    {active === "Asset Allocation" && <AllocationAdvisor />}
    {active === "Strategy Lab" && <div className="feature-grid"><Card className="tool-card"><h2>Create a strategy</h2><label>Symbol<input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())} /></label><label>Risk profile<select><option>Medium</option><option>Low</option><option>High</option></select></label><label>Trading style<select><option>Swing</option><option>Intraday</option><option>Positional</option><option>Long Term</option></select></label><p className="form-label">INDICATORS</p><div className="chips">{["RSI","MACD","EMA","VWAP","Bollinger","ADX","ATR"].map(i=><button key={i} className={selected.includes(i)?"chip selected-chip":"chip"} onClick={()=>toggle(i)}>{selected.includes(i)?"✓ ":""}{i}</button>)}</div><button className="primary" onClick={()=>run(`${symbol} strategy generated · Buy zone ₹2,928 · Target ₹3,055 · Stop ₹2,870 · 73% probability`)}>Generate AI strategy <span>✦</span></button></Card><Card className="result-card"><p className="eyebrow">EXPLAINABLE OUTPUT</p><h2>{result ? "Strategy ready" : "Your AI strategy will appear here"}</h2><div className="empty-result">{result || "Select your risk, style and preferred indicators, then generate a research-backed trade plan."}</div>{result && <div className="metric-row"><span>Market condition <b>Bullish continuation</b></span><span>Holding time <b>3–7 days</b></span></div>}</Card></div>}
    {active === "Market Doctor" && <div className="feature-grid"><Card className="tool-card"><h2>Analyze your portfolio</h2><label>Holdings (comma-separated)<textarea placeholder="RELIANCE, TCS, HDFCBANK, INFY" /></label><label>Investment horizon<select><option>Long term</option><option>Swing</option><option>Intraday</option></select></label><button className="primary" onClick={()=>run("Portfolio score 82/100 · Moderate risk · Good diversification. AI suggests reducing financial concentration and adding healthcare/FMCG exposure.")}>Run Market Doctor <span>✦</span></button></Card><Card className="result-card"><p className="eyebrow">PORTFOLIO DIAGNOSIS</p><h2>{result ? "Healthy, with one alert" : "No diagnosis yet"}</h2><div className="empty-result">{result || "Add holdings to receive risk, diversification, drawdown, beta and correlation analysis."}</div></Card></div>}
    {active === "Backtesting" && <div className="feature-grid"><Card className="tool-card"><h2>Validate a strategy</h2><label>Symbol<input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/></label><label>Strategy<select><option>Moving Average Crossover</option><option>Momentum</option><option>Mean Reversion</option><option>Breakout</option></select></label><label>Test period<select><option>Last 2 years</option><option>Last 1 year</option><option>Last 5 years</option></select></label><button className="primary" onClick={()=>run(`${symbol} test complete · 34 trades · 61.8% win rate · +18.4% net return · −7.2% maximum drawdown · Sharpe 1.43`)}>Run backtest <span>▶</span></button></Card><Card className="result-card"><p className="eyebrow">WALK-FORWARD VALIDATION</p><h2>{result ? "Backtest complete" : "Ready to test"}</h2><div className="empty-result">{result || "Runs should use out-of-sample data and include transaction costs before interpreting results."}</div></Card></div>}
    {active === "News Intel" && <Card className="feed-card"><div className="filter-row"><button className="chip selected-chip">All news</button><button className="chip">Bullish</button><button className="chip">Bearish</button><button className="chip">Macro</button></div>{news.concat([["Corporate", "IT sector guidance improves after latest global demand data", "Bullish", "74"], ["Macro", "Oil prices rise ahead of central-bank decisions", "Neutral", "59"]]).map(([tag,title,mood,score])=><article key={title}><span className="news-tag">{tag}</span><div><h3>{title}</h3><p>AI summary: This development may influence the affected sector over the next few sessions.</p><small>Impact <b className={mood === "Bullish" ? "mint-text" : "amber"}>{mood}</b> · Confidence {score}%</small></div><button className="outline-button" onClick={()=>run(`Saved: ${title}`)}>Save</button></article>)}{result&&<p className="toast">{result}</p>}</Card>}
    {active === "Community" && <div className="feature-grid"><Card><p className="eyebrow">REDDIT + STOCKTWITS</p><h2>Community sentiment <span className="mint-text">64% bullish</span></h2><div className="sentiment-mini"><b>RELIANCE</b><span>▲ 71% bullish</span><b>TATAMOTORS</b><span>▲ 68% bullish</span><b>INFY</b><span>— 52% neutral</span></div></Card><Card className="result-card"><p className="eyebrow">TRENDING DISCUSSIONS</p><h3>Bank Nifty breaks out after a strong opening.</h3><p>r/IndianStreetBets · AI sentiment: <b className="mint-text">Bullish</b></p><hr/><h3>Traders are watching IT earnings guidance.</h3><p>Stocktwits · AI sentiment: Neutral</p></Card></div>}
    {active === "Markets" && <><div className="chart-section"><LiveCandlestickChart /></div><div className="feature-grid"><Card><p className="eyebrow">CORRELATION ENGINE</p><h2>Market relationships</h2><div className="heatmap">{["NIFTY","SENSEX","BANK","GOLD","USDINR","VIX"].map((a,i)=><div key={a}><b>{a}</b>{[.96,.84,.62,.22,-.18,-.58].map((v,j)=><i key={j} style={{opacity:Math.abs(v)-(i===j?0:.1)}}>{i===j?"1.0":v}</i>)}</div>)}</div><p className="sub">Nifty and Sensex remain tightly correlated; VIX has an inverse relationship with equity indices.</p></Card><Card className="result-card"><p className="eyebrow">SECTOR ROTATION</p><h2>Leaders today</h2><div className="rank"><span>1</span> Banking <b>+1.8%</b><span>2</span> Auto <b>+1.2%</b><span>3</span> IT <b>+0.9%</b></div></Card></div></>}
    {active === "Forecast Accuracy" && <div className="feature-grid"><Card><p className="eyebrow">XGBOOST V2.1 / MODEL HEALTHY</p><h2>71.4% direction accuracy</h2><div className="accuracy"><div><b>1.87</b><span>Mean absolute error</span></div><div><b>2.64</b><span>RMSE</span></div><div><b>0.82</b><span>Confidence calibration</span></div></div><div className="mini-bars big-bars">{bars.map((x,i)=><i key={i} style={{height:`${x}%`}} className={i>7?"hot":""}/>)}</div></Card><Card className="result-card"><p className="eyebrow">LATEST FORECAST</p><h2>NIFTY 50</h2><div className="empty-result">Yesterday prediction: <b className="mint-text">UP</b><br/>Actual close: 22,493.55<br/>Prediction error: 0.63%<br/><br/>The model is performing within its expected volatility band.</div></Card></div>}
    {active === "Watchlist" && <Card className="watch-card"><div className="card-title"><div><p>PERSONAL WATCHLIST</p><h2>Research queue</h2></div><button className="add" onClick={()=>run("New stock added to watchlist")}>+ Add symbol</button></div><div className="stock-table">{stocks.concat([["TATAMOTORS","₹1,014.20","+1.94%","up"]]).map(([name,price,change,dir])=><div key={name}><span className="stock-logo">{name[0]}</span><b>{name}<small>NSE</small></b><strong>{price}</strong><span className={dir}>{change}</span><Sparkline positive={dir==="up"}/><button onClick={()=>run(`${name} alert configured`)}>⋮</button></div>)}</div>{result&&<p className="toast">{result}</p>}</Card>}
    {active === "Economic Calendar" && <Card className="feed-card"><p className="eyebrow">UPCOMING EVENTS</p>{[["SEP 10","RBI monetary policy meeting","High"],["SEP 12","India CPI inflation release","High"],["SEP 18","US FOMC rate decision","High"],["SEP 24","Reliance quarterly results","Medium"]].map(([date,event,impact])=><article key={event}><span className="news-tag">{date}</span><div><h3>{event}</h3><p>AI expected impact: volatility may increase around the release. Review exposure and event risk.</p></div><span className={impact==="High"?"pill red-text":"pill amber"}>{impact} impact</span></article>)}</Card>}
    {active === "Scenario Lab" && <div className="feature-grid"><Card className="tool-card"><h2>Run a market scenario</h2><label>Scenario<select><option>RBI cuts rates by 25 bps</option><option>Crude oil rises 10%</option><option>USDINR falls 3%</option><option>Gold rises 5%</option></select></label><label>Horizon<select><option>1 month</option><option>1 week</option><option>3 months</option></select></label><button className="primary" onClick={()=>run("Scenario result: Banking and rate-sensitive sectors may benefit; INR-sensitive exporters could face pressure. Confidence: medium.")}>Simulate impact ✦</button></Card><Card className="result-card"><p className="eyebrow">AI SCENARIO ANALYSIS</p><h2>{result ? "Possible market reaction" : "Select a scenario"}</h2><div className="empty-result">{result || "MarketMind will explain likely sector, index and portfolio effects. Scenarios are exploratory research, not forecasts."}</div></Card></div>}
    {active === "Learning" && <div className="learn-grid">{[["RSI","Understand momentum and overbought/oversold zones."],["MACD","Read trend changes using moving-average convergence."],["Risk management","Position size, stops and drawdown discipline."],["Candlesticks","Learn price-action patterns in context."]].map(([name,copy])=><Card key={name}><span className="feature-icon">◇</span><h2>{name}</h2><p>{copy}</p><button className="link" onClick={()=>run(`Lesson opened: ${name}. The AI Mentor is ready to explain it.`)}>Start lesson →</button></Card>)}{result&&<p className="toast">{result}</p>}</div>}
    <Card className="mentor"><div><span className="feature-icon">✦</span><div><p className="eyebrow">AI MARKET MENTOR</p><h3>Ask anything about the markets</h3></div><span className={mentorLoading ? "mentor-status thinking" : "mentor-status"}>{mentorLoading ? "Thinking…" : "● Online"}</span></div><div className="mentor-prompts">{["Explain RSI in simple words", "What does MACD tell me?", "Why is Nifty moving today?", "How do I diversify my portfolio?"].map(prompt=><button type="button" key={prompt} onClick={()=>askMentor(prompt)}>{prompt}</button>)}</div><div className="chat-log" aria-live="polite">{messages.map((m,i)=><div className={m.from === "You" ? "chat-message user-message" : "chat-message"} key={i}><b>{m.from}</b><p>{m.text}</p></div>)}{mentorLoading && <div className="chat-message"><b>AI Mentor</b><p className="typing">Thinking<span>.</span><span>.</span><span>.</span></p></div>}</div>{mentorError && <p className="mentor-error">{mentorError}</p>}<form onSubmit={e=>{e.preventDefault();askMentor()}}><input value={chat} onChange={e=>setChat(e.target.value)} disabled={mentorLoading} placeholder="e.g. Explain why Nifty is rising today"/><button className="primary" disabled={mentorLoading}>{mentorLoading ? "Thinking…" : "Ask AI →"}</button></form><small className="mentor-disclaimer">Educational research only. The mentor does not provide financial advice.</small></Card>
    <footer><span>⚠ Predictions are AI-generated research insights and should not be considered financial advice.</span><span>MarketMind AI · v0.1.0</span></footer>
  </div>
}

function AllocationAdvisor() {
  const [amount, setAmount] = useState(500000);
  const [risk, setRisk] = useState("Moderate");
  const [goal, setGoal] = useState("Wealth Creation");
  const [horizon, setHorizon] = useState("3 Years");
  const [market, setMarket] = useState("Indian Market");
  const [signal, setSignal] = useState("Current conditions");
  const allocation = useMemo(() => {
    const base: Record<string, [string, number, string][]> = {
      Conservative: [["Gold",25,"#f2bd55"],["Nifty 50",25,"#58dca4"],["FMCG",10,"#68aef7"],["Pharma",10,"#b98cf5"],["IT",5,"#ff8f9b"],["Silver",5,"#bbc7d1"],["Cash",20,"#64748b"]],
      Moderate: [["Gold",15,"#f2bd55"],["Nifty 50",25,"#58dca4"],["Bank Nifty",10,"#68aef7"],["IT",10,"#b98cf5"],["Auto",7,"#ff8f9b"],["Pharma",8,"#77cdb5"],["Midcap",10,"#5e83e7"],["Silver",5,"#bbc7d1"],["Cash",10,"#64748b"]],
      Aggressive: [["Nifty 50",25,"#58dca4"],["Midcap",15,"#5e83e7"],["Smallcap",10,"#b98cf5"],["IT",12,"#ff8f9b"],["Banking",10,"#68aef7"],["Auto",8,"#77cdb5"],["Pharma",5,"#cb92f4"],["Gold",5,"#f2bd55"],["Silver",5,"#bbc7d1"],["Cash",5,"#64748b"]]
    };
    const values = base[risk].map(x => [...x] as [string,number,string]);
    const move = (from:string,to:string,p:number) => { const f=values.find(x=>x[0]===from); const t=values.find(x=>x[0]===to); if(f&&t){f[1]-=p;t[1]+=p;} };
    if(signal === "VIX spike") move(values.some(x=>x[0] === "Bank Nifty") ? "Bank Nifty" : "Nifty 50", "Cash", 5);
    if(signal === "Gold bullish") move("Cash", "Gold", 5);
    if(signal === "RBI rate cut") move("Gold", "Bank Nifty", 5);
    if(signal === "Banking weak") move(values.some(x=>x[0] === "Bank Nifty") ? "Bank Nifty" : "Banking", "Cash", 5);
    if(signal === "IT earnings improve") move("Cash", "IT", 5);
    return values;
  },[risk,signal]);
  const total = allocation.reduce((sum,x)=>sum+x[1],0);
  const pie = `conic-gradient(${allocation.reduce((s,x,i)=>{const start=allocation.slice(0,i).reduce((a,v)=>a+v[1],0);return `${s}${x[2]} ${start}% ${start+x[1]}%,`;},"").slice(0,-1)})`;
  const fmt = new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
  const expected = risk === "Conservative" ? "8–11%" : risk === "Moderate" ? "11–15%" : "14–21%";
  const volatility = risk === "Conservative" ? "9.5%" : risk === "Moderate" ? "14.2%" : "21.8%";
  return <div className="allocation-page">
    <div className="allocation-layout"><Card className="tool-card allocation-form"><p className="eyebrow">PERSONALIZED ALLOCATION</p><h2>Build your investment plan</h2><label>Investment amount<input type="number" min="1000" value={amount} onChange={e=>setAmount(Math.max(0,Number(e.target.value)))} /></label><label>Risk profile<select value={risk} onChange={e=>setRisk(e.target.value)}><option>Conservative</option><option>Moderate</option><option>Aggressive</option></select></label><label>Investment goal<select value={goal} onChange={e=>setGoal(e.target.value)}><option>Wealth Creation</option><option>Retirement</option><option>Swing Trading</option><option>Monthly Income</option><option>Capital Preservation</option></select></label><label>Investment horizon<select value={horizon} onChange={e=>setHorizon(e.target.value)}>{["1 Week","1 Month","3 Months","6 Months","1 Year","3 Years","5 Years"].map(x=><option key={x}>{x}</option>)}</select></label><label>Preferred market<select value={market} onChange={e=>setMarket(e.target.value)}><option>Indian Market</option><option>US Market</option><option>Global</option></select></label><p className="form-label">DYNAMIC REBALANCE SIGNAL</p><div className="chips">{["Current conditions","VIX spike","Gold bullish","RBI rate cut","Banking weak","IT earnings improve"].map(x=><button type="button" onClick={()=>setSignal(x)} className={signal===x?"chip selected-chip":"chip"} key={x}>{x}</button>)}</div></Card>
      <Card className="allocation-summary"><div className="card-title"><div><p>AI RECOMMENDATION</p><h2>{risk} allocation <span className="pill green">{total}% allocated</span></h2></div><span className="live"><span/> LIVE SIGNALS</span></div><div className="allocation-hero"><div className="pie" style={{background:pie}}><div><b>{total}%</b><small>invested</small></div></div><div className="summary-copy"><b>{fmt.format(amount)}</b><span>recommended capital</span><p>Built for <strong>{goal}</strong> over <strong>{horizon}</strong> in the <strong>{market}</strong>.</p><div className="confidence"><span>AI confidence</span><b>78 / 100</b><i><em/></i></div></div></div><div className="allocation-list">{allocation.map(([name,percent,color])=><div key={name}><i style={{background:color}}/><b>{name}</b><span>{fmt.format(amount*percent/100)}</span><strong>{percent}%</strong></div>)}</div></Card></div>
    <div className="grid allocation-metrics"><Card><p className="eyebrow">PORTFOLIO HEALTH</p><b className="large-metric">84<span>/100</span></b><p className="mint-text">Well diversified</p></Card><Card><p className="eyebrow">EXPECTED RETURN</p><b className="large-metric">{expected}</b><p>Annualized research range</p></Card><Card><p className="eyebrow">EXPECTED VOLATILITY</p><b className="large-metric">{volatility}</b><p>Risk-adjusted estimate</p></Card><Card><p className="eyebrow">MAX DRAWDOWN</p><b className="large-metric red-text">−{risk === "Aggressive" ? "18" : risk === "Moderate" ? "12" : "7"}%</b><p>Historical stress estimate</p></Card><Card><p className="eyebrow">SHARPE ESTIMATE</p><b className="large-metric">{risk === "Aggressive" ? "1.18" : risk === "Moderate" ? "1.36" : "1.22"}</b><p>Return per unit of risk</p></Card></div>
    <div className="grid allocation-bottom"><Card><p className="eyebrow">AI REASONING</p><h2>Why this mix</h2><div className="reasoning"><div><b>Gold · {allocation.find(x=>x[0]==="Gold")?.[1] || 0}%</b><p>Gold provides a diversification hedge while volatility and macro uncertainty remain elevated.</p></div><div><b>Nifty 50 · {allocation.find(x=>x[0]==="Nifty 50")?.[1] || 0}%</b><p>Broad-market exposure participates in the prevailing uptrend without single-stock concentration.</p></div><div><b>Cash · {allocation.find(x=>x[0]==="Cash")?.[1] || 0}%</b><p>Liquidity protects capital and preserves flexibility around calendar-driven volatility.</p></div></div><p className="rebalance-note">✦ Dynamic rebalance active: <b>{signal}</b>. Review this allocation when macro conditions or your goals change.</p></Card><Card><p className="eyebrow">SECTOR ROTATION ENGINE</p><h2>Forward-looking sector posture</h2>{[["Technology","Bullish","72%"],["Pharma","Bullish","76%"],["Banking","Neutral","58%"],["Auto","Bullish","67%"]].map(([sector,status,chance])=><div className="rotation" key={sector}><b>{sector}</b><span className={status==="Bullish"?"pill green":"pill amber"}>{status}</span><strong>{chance} probability</strong><small>next 20 days</small></div>)}</Card><Card><p className="eyebrow">HISTORICAL COMPARISON</p><h2>Similar allocation regimes</h2><div className="historical"><span>Backtested return <b className="mint-text">+14.8%</b></span><span>Maximum drawdown <b className="red-text">−10.6%</b></span><span>Sharpe ratio <b>1.31</b></span><span>Positive periods <b>68%</b></span></div><button className="outline-button">Open full allocation backtest →</button></Card></div>
    <p className="allocation-disclaimer">⚠ Allocation recommendations are AI-generated research insights and should not be considered financial advice. Historical performance does not guarantee future results.</p>
  </div>
}
